In [79]:
import pandas as pd
import requests
from bs4 import BeautifulSoup


In [80]:
count = 1

while count <= 5:
    print(count)
    count = count + 1


1
2
3
4
5


In [81]:
url = "https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category"

In [82]:
page = 1
number_of_pages = 5

while page <= number_of_pages:
    page = page + 1
    print(page)

2
3
4
5
6


In [83]:
page = 1
number_of_pages = 278

url = "https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category"

pagelist = []
pagelist.append(url)

while page <= number_of_pages:
    page = page + 1
    pagestr = str(page)
    nextpage = url + "&page=" + pagestr

    pagelist.append(nextpage)
    
pagelist

['https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=2',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=3',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=4',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=5',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=6',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=7',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=8',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=9',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=10',
 'https://www.kilimall.co.ke/category/computers-accessories?id=349&form=category&page=11',
 'https://www.k

In [84]:
for x in range(2, 21, 2):
    print(x)

2
4
6
8
10
12
14
16
18
20


In [85]:
employees = ["John", "Andrew", "Mark"]

In [86]:
phone = {
    "Brand": "Samsung",
    "Price": 3000,
    "Color": "Red"
    }

print(phone)

{'Brand': 'Samsung', 'Price': 3000, 'Color': 'Red'}


In [87]:
car = {
    "Brand": "Toyota",
    "Model": "Landcruiser V8",
    "Year": 2018,
    "Colors": ["red", "Blue", "Pink"]
}

print(car["Colors"])

y=car.get("Model")

x = car.keys()
x
z = car.values()
s = car.items()

print (s)

if "Model" in car:
    print("exists")

['red', 'Blue', 'Pink']
dict_items([('Brand', 'Toyota'), ('Model', 'Landcruiser V8'), ('Year', 2018), ('Colors', ['red', 'Blue', 'Pink'])])
exists


In [88]:
car["Model"] = "Nissan"
car

{'Brand': 'Toyota',
 'Model': 'Nissan',
 'Year': 2018,
 'Colors': ['red', 'Blue', 'Pink']}

In [89]:
car["Engine size"] = "5400cc"
car

{'Brand': 'Toyota',
 'Model': 'Nissan',
 'Year': 2018,
 'Colors': ['red', 'Blue', 'Pink'],
 'Engine size': '5400cc'}

In [90]:
car.popitem()
car

{'Brand': 'Toyota',
 'Model': 'Nissan',
 'Year': 2018,
 'Colors': ['red', 'Blue', 'Pink']}

In [91]:
del car["Year"]

In [92]:
car

{'Brand': 'Toyota', 'Model': 'Nissan', 'Colors': ['red', 'Blue', 'Pink']}

In [93]:
car.clear()
car

{}

In [94]:
phone

{'Brand': 'Samsung', 'Price': 3000, 'Color': 'Red'}

In [95]:
for x in phone:
    print(phone[x])

Samsung
3000
Red


In [96]:
for x in phone.keys():
    print(x)

Brand
Price
Color


In [97]:
children = {
"child1": {
    "name": "Purity",
    "age": 21
},
"child2": {
    "name" : "Jane",
    "age": 25
},
"child3":{
    "name": "Alpha",
    "Age": "45"
}
}

children

{'child1': {'name': 'Purity', 'age': 21},
 'child2': {'name': 'Jane', 'age': 25},
 'child3': {'name': 'Alpha', 'Age': '45'}}

In [98]:
#Recursion

def tri_recursion(k):
    if (k > 0):
        results = k + tri_recursion(k - 1)
        print(results)
        return results
    else:
        return 0
    
print("Recursion Example results")

tri_recursion(8)


Recursion Example results
1
3
6
10
15
21
28
36


36

In [99]:
def multiply(a , /):
    return 5 + a

multiply(5)

10

In [100]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry


In [101]:
import numpy as np

In [102]:
arr  = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [103]:
arr3 = np.array([[5,7,5], [3,4,5]])
print(arr3)

[[5 7 5]
 [3 4 5]]


Create a 2D NumPy array named grades with 5 students and 4 subjects (Mathematics, Science, English, and History). Each entry should be a random number between 40 and 100 (inclusive).

Print the grades array.

In [104]:
arr4 = np.random.randint(40, 100, (5, 4))
print(arr4)

[[53 89 97 48]
 [65 92 41 59]
 [67 86 99 46]
 [83 47 86 74]
 [53 56 75 89]]


Print the grades of the third student (index 2).


In [105]:
print(arr4[2])

[67 86 99 46]


Print the Science grades (second column).


In [106]:
print(arr4[:, 1])

[89 92 86 47 56]


Print the grades of the last two students.


In [107]:
print(arr4)

[[53 89 97 48]
 [65 92 41 59]
 [67 86 99 46]
 [83 47 86 74]
 [53 56 75 89]]


In [108]:
print(arr4[-2 : ])

[[83 47 86 74]
 [53 56 75 89]]


Print the highest grade obtained by the second student.

In [109]:
print(arr4)
max_arr = arr4[1].max()
print(max_arr)

[[53 89 97 48]
 [65 92 41 59]
 [67 86 99 46]
 [83 47 86 74]
 [53 56 75 89]]
92


-----> Loop through each student’s grades and print whether they passed or failed each subject. A passing grade is 50 or above.

In [110]:
students_passed = []
for x in arr4.flat:
    if x > 50:
        students_passed.append(arr4)
        print("students_passed")
    elif x < 50:
        students_passed.append(arr4)
        print("Failed")


students_passed
students_passed
students_passed
Failed
students_passed
students_passed
Failed
students_passed
students_passed
students_passed
students_passed
Failed
students_passed
Failed
students_passed
students_passed
students_passed
students_passed
students_passed
students_passed


 ----> Calculate and print the average grade for each student.

In [111]:
#Students score
student1 = arr4[0].mean()
student2 = arr4[1].mean()
student3 = arr4[2].mean()
student4 = arr4[3].mean()
student5 = arr4[4].mean()
print(student1)
print(student2)
print(student3)
print(student4)
print(student5)


71.75
64.25
74.5
72.5
68.25


In [122]:
average_grades = np.mean(arr4, axis=1)
print(average_grades)

[71.75 64.25 74.5  72.5  68.25]


Find and print the name of the student with the highest average grade. Assume student names are stored in a list:


In [ ]:
np.random.seed(42)  # For reproducibility

# List of student names
student_names = ["Alice", "Bob", "Charlie", "David", "Eve"]

# Calculate the average grade for each student
average_grades = np.mean(arr4, axis=1)

# Find the highest average grade
max_avg = np.max(average_grades)

# Find the student(s) with the highest average
highest_students = [name for name, avg in zip(student_names, average_grades) if avg == max_avg]

# Print results
print("Grades Array:\n", arr4)
print("\nAverage Grades:", average_grades)
print("\nStudent(s) with the highest average grade:", ", ".join(highest_students))
print("Highest average grade:", max_avg)


Grades Array:
 [[53 89 97 48]
 [65 92 41 59]
 [67 86 99 46]
 [83 47 86 74]
 [53 56 75 89]]

Average Grades: [71.75 64.25 74.5  72.5  68.25]

Student(s) with the highest average grade: Charlie
Highest average grade: 74.5


Find and print the number of students who failed at least one subject.


In [ ]:
students_failed_one = np.any(arr4 < 50, axis=1)

number_students_failed = np.sum(students_failed_one)
print(f"Number of students who failed: {number_students_failed}")

Number of students who failed: 4


**Advanced Analysis**

Find and print the highest grade in each subject.


In [ ]:
subjects  = ["Mathematics", "Science", "English", "History"]

max_grade = np.max(arr4, axis=0)

for subject, grade in zip(subjects, max_grade):
    print(f"{subject}: {grade}")

Mathematics: 83
Science: 92
English: 99
History: 89


In [116]:
# Determine students who passed all subjects (grade >= 50)
students_passed = np.all(arr4 >= 50, axis=1)

# Count the number of students who passed all subjects
num_passed_all = np.sum(students_passed)

num_passed_all

np.int64(1)

Print the highest grade obtained by the second student.


In [128]:
secondstudentmax = np.max(arr4[1])

secondstudentmax


np.int32(92)

Convert the numerical grades into letter grades using the following scale:

* 90-100 → A
* 80-89 → B
* 70-79 → C
* 60-69 → D
* 50-59 → E
* Below 50 → F

Use loops and conditionals to replace numeric grades with letter grades in a new array

In [132]:
for y in arr4.flat:
    if y >=90 and y <=100:
        print ("A")
    elif y >=80 and y <=89:
        print("B")
    elif y >=70 and y <=79:
        print("C")
    elif y >=60 and y <=69:
        print("D")
    elif y >=50 and y <=59:
        print("E")
    else:
        print("F")

E
B
A
F
D
A
F
E
D
B
A
F
B
F
B
C
E
E
C
B
